### ISSUE TITLE
Build failure on Windows R 4.1.3

### ISSUE THREAD

**Issue by nicholascarey** [tidyverse/purrr#1044] opened 2023-01-08 11:24 UTC
My package has a build failure involving `purrr` on Windows R 4.1.3 as seen here: 

https://github.com/januarharianto/respR/actions/runs/3855946796

All other OSs and versions build fine. The actual error is - 

`DLL 'purrr' not found: maybe not installed for this architecture?`

As far as i can tell from the log it installs ok, but then is not found. Sorry if this is not the right place to bring this up and is a issue with my setup and not `purrr` itself. I'm just using a standard GH actions script from [r-lib/actions](https://github.com/r-lib/actions).

**Comment by hadley** [comment] 2023-01-08 16:31
Duplicate of #1039

**Closed by hadley** 2023-01-08 16:31 UTC
