### ISSUE TITLE
POSIXct objects get converted to numeric objects when using the pmap function

### ISSUE THREAD

**Issue by RenBinary** [tidyverse/purrr#442] opened 2018-01-10 05:58 UTC
require(tidyverse)
require(lubridate)

pmap(list(x = ymd_hms('20180110 000000')),function(x){class(x)})

**Comment by cderv** [comment] 2018-01-10 06:56
For future reference, I think this is duplicated or related to #251 and #358

**Comment by hadley** [comment] 2018-01-16 02:30
Yeah, duplicate of #358

**Closed by hadley** 2018-01-16 02:30 UTC
