### ISSUE TITLE
transpose & flatten declasses (at least `dttm` objects)

### ISSUE THREAD

**Issue by mmuurr** [tidyverse/purrr#803] opened 2020-11-15 06:21 UTC
Using purrr v0.3.4, when I transpose a data.frame with a datetime column, that column is de-classed:
```R
> x <- tibble(now = Sys.time())

> x
# A tibble: 1 x 1
#   now
#   <dttm>
# 1 2020-11-14 23:12:35

> transpose(x)
# [[1]]
# [[1]]$now
# [1] 1605420756
```
Is this expected?

**Comment by mmuurr** [comment] 2020-11-15 06:35
I've just noticed that `flatten` does the same thing:
```R
> list(Sys.time())
# [[1]]
# [1] "2020-11-14 23:34:39 MST"

> list(Sys.time()) %>% flatten()
# [[1]]
# [1] 1605422083
```

**Comment by lionel-** [comment] 2020-11-16 09:28
This will be fixed once we implement purrr on top of vctrs.

**Comment by jonathan-g** [comment] 2021-01-16 23:27
In the meantime, I have found that `purrr::pmap(list)` is a workaround for turning a `tibble` into a list of rows (i.e., a list of lists where each element of the outer list is a row of the original tibble).

``` r
library(purrr)
library(tibble)

foo <- tibble(now = Sys.time())
foo
#> # A tibble: 1 x 1
#>   now                
#>   <dttm>             
#> 1 2021-01-16 17:25:02

purrr::transpose(foo)
#> [[1]]
#> [[1]]$now
#> [1] 1610839503

purrr::pmap(foo, list)
#> [[1]]
#> [[1]]$now
#> [1] "2021-01-16 17:25:02 CST"
```

<sup>Created on 2021-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Acknowledgements
@jennybc's [fabulous tutorials on data rectangling](https://rstudio.com/resources/rstudioconf-2018/data-rectangling/) led me to this solution.

**Comment by hadley** [comment] 2022-08-24 09:11
Duplicate of #471, which has moved to #875

**Closed by hadley** 2022-08-24 09:11 UTC
