### ISSUE TITLE
list_modify and list_merge produce identical results when called on nested lists

### ISSUE THREAD

**Issue by afoltzm** [tidyverse/purrr#816] opened 2021-01-22 19:21 UTC
## Issue type
Bug report

## Problem statement + expected behavior
I'm trying to use `list_modify` to update values in a named list, some of which are lists themselves, using the `!!!` syntax to splice in list values. Per the documentation, I am expecting the value to be replaced:

> If a sub-element is present in both lists `list_modify()` takes the value from `y`, and `list_merge()` concatenates the values together.

However, this is not what I'm seeing. `list_modify` is concatenating the nested lists instead of replacing them. This is observed on `purrr` 0.3.4 with R 3.6.3 on Ubuntu 20.04.

## reprex
```r
library(purrr)
list_modify(list(a=list(b=1,c=2)), !!!list(a=list(d=3)))
> $a
> $a$b
> [1] 1
> $a$c
> [1] 2
> $a$d
> [1] 3

list_merge(list(a=list(b=1,c=2)), !!!list(a=list(d=3)))
> $a
> $a$b
> [1] 1
> $a$c
> [1] 2
> $a$d
> [1] 3
```

**Comment by afoltzm** [comment] 2021-01-22 20:10
N.B. for those looking for a workaround - the following function produces expected behavior on both simple and nested lists.

```r
list_update <- function(x, y) {
  purrr::map2(x, names(x), function(val, name) {
    if(name %in% names(y)) y[[name]] else val
  })
}
```

**Comment by hadley** [comment] 2022-08-24 07:48
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by hadley** [comment] 2022-08-27 13:52
Oooh, the problem is the recursion, so this is a duplicate of #822.

**Closed by hadley** 2022-08-27 13:52 UTC
Labels: reprex, list 🧦
