### ISSUE TITLE
`modify_if()` methods are missing `.else`

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/purrr#786] opened 2020-08-10 16:48 UTC
The generic and default method have `.else`

https://github.com/tidyverse/purrr/blob/5de5ad293b817d8a6baea32cc4415487d71da955/R/modify.R#L215-L237

**Comment by hadley** [comment] 2022-08-24 14:05
Duplicate of #701

**Closed by hadley** 2022-08-24 14:05 UTC
Labels: bug, modify :hammer_and_wrench:
