### ISSUE TITLE
pmap returns output length zero if at least one element is length 0

### ISSUE THREAD

**Issue by benjaminschwetz** [tidyverse/purrr#695] opened 2019-07-31 18:01 UTC
Edit: related to #679 

Regarding inputs of length 0, the documentation for `pmap()` / `map2()` states under values: 

> If all input is length 0, the output will be length 0. 

I deducted from this statement that the output would not be length zero, if all inputs would not be 0. I.e. `NULL`s would be passed on to the functions together with the other elements. However, if I pass a list with at least one element of length 0, to `pmap()`, the output is length 0.

``` r
l <- list(letters, LETTERS, NULL)
x <- purrr::pmap(l,c)
x
#> list()
#What I would expect x to look like:
list(
  c(letters[1], LETTERS[1], NULL),
  c(letters[2], LETTERS[2], NULL),
  c(letters[3], LETTERS[3], NULL)
  # etc.
)
#> [[1]]
#> [1] "a" "A"
#> 
#> [[2]]
#> [1] "b" "B"
#> 
#> [[3]]
#> [1] "c" "C"
```

<sup>Created on 2019-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment] 2019-10-15 15:31
In the future this will probably become an error. We have adopted the rule that only length 1 vectors can be recycled. See discussion in https://github.com/tidyverse/principles/issues/13

**Comment by hadley** [comment] 2022-08-27 13:31
Now duplicate of #878

**Closed by hadley** 2022-08-27 13:31 UTC
Labels: bug, map :world_map:
