### ISSUE TITLE
pluck doesn't work with built-in functions

### ISSUE THREAD

**Issue by dgrtwo** [tidyverse/purrr#404] opened 2017-11-05 16:26 UTC
While `pluck` works with base functions such as `toupper`, it doesn't work with functions such as `as.character` or `is.numeric`, giving a "must be a character or numeric vector" error.

As far as I can tell, the difference is whether `typeof()` returns "closure" (always works) or "builtin" (doesn't work).

``` r
library(purrr)
x <- list(a = "apple", n = 3, v = 1:5)

# Using a closure works
typeof(toupper)
#> [1] "closure"
pluck(x, "a")
#> [1] "apple"
pluck(x, "a", toupper)
#> [1] "APPLE"

# but using a builtin doesn't
typeof(as.character)
#> [1] "builtin"
pluck(x, "n")
#> [1] 3
pluck(x, "n", as.character)
#> Error: Index 2 must be a character or numeric vector
pluck(x, "n", is.double)
#> Error: Index 2 must be a character or numeric vector

# It would have worked if we defined it in a function
f.1 <- function(x) as.character(x)
pluck(x, "n", f.1)
#> [1] "3"
```

**Comment by lionel-** [comment] 2017-11-05 16:35
Thanks, this is a duplicate of #370. We need to evaluate the accessors in the calling environment so that lexically scoped methods (such as those of the base package which aren't registered) can be found.

**Comment by lionel-** [comment] 2017-11-05 16:35
Thanks, this is a duplicate of #370. We need to evaluate the accessors in the calling environment so that lexically scoped methods (such as those of the base package which aren't registered) can be found.

**Comment by dgrtwo** [comment] 2017-11-05 16:42
Ah! Hadn't realized it was the same issue, thanks.

**Comment by lionel-** [comment] 2017-11-05 16:51
I'm sorry I read your report too fast, it does look like a different issue.

**Closed** 2018-11-30 13:47 UTC
Labels: bug, pluck :pear:
