### ISSUE TITLE
Performance issue: purrr::flatten

### ISSUE THREAD

**Issue by JLHerreraCortijo** [tidyverse/purrr#1102] opened 2023-09-22 09:11 UTC
After purrr::flatten has been superseded, something is impacting its performance. When you profile this code

```r
for(i in 1:1000){
 x <-  purrr::flatten(list(a=list(1,2,3),b=list("a","b","c")))
  
}
```
 The data shows a call to utils::readCitationFile() consuming much time.
 
Platform: posit cloud
RStudio version: RStudio Pro 2023.06.1 Build 524.pro1
R version output:
``` 
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.1                         
year           2023                        
month          06                          
day            16                          
svn rev        84548                       
language       R                           
version.string R version 4.3.1 (2023-06-16)
nickname       Beagle Scouts   
```

**Comment by hadley** [comment] 2023-11-01 17:48
Duplicate of https://github.com/r-lib/lifecycle/issues/167

**Closed by hadley** 2023-11-01 17:48 UTC
