### ISSUE TITLE
More helpful error message from `map_dfc()` when `.x` has no names

### ISSUE THREAD

**Issue by wlandau** [tidyverse/purrr#451] opened 2018-02-01 18:41 UTC
```r
ms <- 1:3
map_dfc(ms, rnorm, n = 2)

## Error in cbind_all(x) : Not compatible with STRSXP: [type=NULL].
```

As @hadley pointed out, the error comes from the lack of names.

```r
map_dfc(set_names(ms, c("a", "b", "c")), rnorm, n = 2)

## # A tibble: 2 x 3
##       a     b     c
##   <dbl> <dbl> <dbl>
## 1 0.736  3.52  2.84
## 2 1.51   1.13  2.96
```

**Comment by hadley** [comment] 2018-02-04 23:32
Duplicate of #395

**Closed by hadley** 2018-02-04 23:32 UTC
Labels: error, feature
