### ISSUE TITLE
modify_in() with zero-length element doesn't modify as expected

### ISSUE THREAD

**Issue by mmuurr** [tidyverse/purrr#811] opened 2020-12-10 22:30 UTC
I think I'd expect `x` and `y` to be the same after this:
```R
x <- list(foo = character(0))
x <- purrr::modify_in(x, "foo", I)
#> Warning in structure(x, class = unique(c("AsIs", oldClass(x)))): Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
#>   Consider 'structure(list(), *)' instead.
x
#> $foo
#> list()

y <- list(foo = I(character(0)))
y
#> $foo
#> character(0)

identical(x,y)
#> [1] FALSE
```
... but instead after the `modify_in`, the `$foo` element is simply removed (which seems like a bug to me).

(BTW, I just tested `modify_at` and that works fine here, and since it's a single-element modification at depth-one, I think I'd expect `modify_at` and `modify_in` to be equivalent in this case?)

<details><summary>Session info</summary>
<p>
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin19.4.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.10_1/lib/libopenblasp-r0.3.10.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] shiny_1.5.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5      rstudioapi_0.11 knitr_1.30     
 [4] whisker_0.4     magrittr_1.5    xtable_1.8-4   
 [7] R6_2.5.0        rlang_0.4.8     fastmap_1.0.1  
[10] tools_3.6.3     xfun_0.19       tinytex_0.24   
[13] miniUI_0.1.1.1  clipr_0.7.0     htmltools_0.5.0
[16] ellipsis_0.3.1  digest_0.6.27   tibble_3.0.3   
[19] lifecycle_0.2.0 crayon_1.3.4    processx_3.4.4 
[22] later_1.1.0.1   purrr_0.3.4     callr_3.5.1    
[25] promises_1.1.1  vctrs_0.3.1     fs_1.4.2       
[28] ps_1.4.0        mime_0.9        evaluate_0.14  
[31] rmarkdown_2.3   reprex_0.3.0    compiler_3.6.3 
[34] pillar_1.4.6    jsonlite_1.7.1  httpuv_1.5.4   
[37] pkgconfig_2.0.3
</p>
</details>

**Comment by hadley** [comment] 2022-08-24 08:33
Duplicate of #480

**Closed by hadley** 2022-08-24 08:33 UTC
